### ISSUE TITLE
Refactor release process based on outputs_for_publishing

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/output-publisher#15]
[OFP 11](https://github.com/opensafely-core/roadmap/discussions/11) adds a new `output_for_publishing` key which explicitly lists output files.

osrelease should use these to improve the release process, taking the opportunity to hide the git details away from the users, and remove the need for Github Desktop authentication in the process.

1. add `osrelease prepare` command. This will create a release directory and copy the files specified by `output_for_publishing` (which will be included in `metadata/`) into it. If it's the first time releasing for this workspace, it also creates a local git repo and copies and commits the files there.

2. The user edits the files in that directory.

3. When ready user runs `osrelease publish`. This prompts the review for a commit message a la git. This then copies the edited files into the local git repo. It uses the diff to generate a redaction log (e.g. "line 23 of file.csv removed", or "output1.png deleted."), commits them with the redaction log using the current windows user as the author. 

4. It then publishes latest version of the results, including redaction.log (via github or job-server depending).

This is very similar to the current process, except: 1) we use the info to copy only the files needed 2) the user just has to edit copied files rather than handle git 3) we use the system user as commit author rather than reaching out to Github for auth.

**Comment by sebbacon** [comment]
Does converting the information implicitly in git (via the commit(s)) into text for a log add much in practice?  

I suppose it then means we could treat the git repo as disposable.

But it also sounds a bit fiddly.

Just thinking aloud.

**Comment by bloodearnest** [comment]
I think we should record the fact a file was redacted by a user, at the very least. For audit, but also for subsequent re-redaction. 
Otherwise, we have no idea if any redaction was done or not.

I think we can easily provide some more metadata with stdlib's `difflib` module easily enough, e.g. how many lines, or which lines. Coupled with the prompt for a commit message, I think that's a useful piece of information to have.

**Comment by bloodearnest** [comment]
Also, the git diff itself cannot be published, obs, but metadata about the diff can.

**Comment by sebbacon** [comment]
>I  think we should record the fact a file was redacted by a user, at the very least. For audit, but also for subsequent re-redaction.
Otherwise, we have no idea if any redaction was done or not.

I guess I was thinking that the fact a file was redacted by a user is stored in the git repo itself.

I guess the difference here is that we're talking about a safe/redacted version of the same info, suitable for release.

Perhaps something like `git diff --compact-summary` (or one of its' relatives) would be sufficient? 

Hah, I just found [this](https://stackoverflow.com/a/9855802/559140) which is quite neat so yeh, not that much faff just to do what you're suggesting anyway...

**Comment by bloodearnest** [comment]
Right, I want to publish the redaction log along side the outputs, so extracting from git somehow. So it's a level of granular public audit, rather than the details git-based private audit trail that only we can access.

**Comment by bloodearnest** [comment]
This has been superseeded by release-hatch
