### ISSUE TITLE
Add primitive safety catch to prevent accidental breach of publication protocol

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/output-publisher#16]
Pending completion of ongoing roles/permissions work (when we will be able enforce that a user has the specific permission to release files), we simply ask people in our documentation to respect the policy. To prevent people releasing stuff because they've not read the policy, we should add a simple token authentication to the tool.

This is not a true security measure, just a trivial process check that the person running the `osrelease` command has access to the token.

Given we plan to do this properly in due course, the implementation might be a `has_permission` function whose implementation can be replaced later, but can for now be an assertion that a particular secret has been typed.  

The user experience would be a prompt, before anything else happens, saying "only members of the core opensafely team can publish outputs. Please email <disclosurecontrol@opensafely.org> to request a release, or enter your password:"

The password could even be hard-coded in the temporary `has_permission` implementation, given it's not a true security feature. It should be shared with the datalab and LSHTM teams.

**Comment by ghickman** [comment]
Done in #20
