### ISSUE TITLE
Ensure entrypoint is available for all users of L4 server

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/output-publisher#3]
`pip install` does work on L4 (which has a vanilla Python installed); however, the entrypoint does not automatically end up on the user's `PATH`.

Furthermore, we want the script to be installed (and updatable) for every user.

See https://github.com/opensafely/cohort-extractor/issues/71#issuecomment-738849281

**Comment by bloodearnest** [comment]
This was done in #6
